### ISSUE TITLE
Warning sign in Feature Comparison table

### ISSUE THREAD

**Issue by roosephu** [dzhang314/MultiFloats.jl#18]
In the Feature Comparison table, there is a warning sign for DoubleFloats on dynamic memory allocation. Could you please elaborate a little bit? Are you referring to the conversion from a Double64 to a (Float64, Float64) pair?  Does this explain why MultiFloats is faster than DoubleFloats (assuming both use the same number of operations)? 

BTW, thanks for making such a performant library with precise code!

**Comment by dzhang314** [comment]
Hey @roosephu, thanks for your interest in **MultiFloats.jl**! I actually removed that warning sign a while ago, but I wanted to write a brief note on its history to close this thread. At one point in the past, I observed some instances where DoubleFloats.jl would allocate in situations where it didn't need to, so I added the warning sign. However, I lost the old version of the benchmark script where I observed this, and I haven't been able to recreate it since. Either this was fixed at some point in DoubleFloats.jl, or my recollection may simply have been mistaken.

In either case, I can no longer substantiate the claim that DoubleFloats.jl makes unnecessary allocations, so I have changed its grade to a check mark.
