### ISSUE TITLE
feature request: make prevfloat and nextfloat accept the optional integer argument

### ISSUE THREAD

**Issue by nsajko** [dzhang314/MultiFloats.jl#39]
See the second argument here, note that it can also be negative or zero: https://docs.julialang.org/en/v1/base/numbers/#Base.nextfloat

A stopgap implementation is obvious: just call `nextfloat`/`prevfloat` repeatedly.

**Comment by dzhang314** [comment]
Hi @nsajko, thanks for your interest in **MultiFloats.jl**! I appreciate this suggestion, but I am intentionally **not** going to support the 2-argument form of `prevfloat`/`nextfloat` because I don't want to give users the impression that I have an efficient implementation.

It is highly nontrivial to implement 2-argument `prevfloat`/`nextfloat` on `MultiFloat` types because the interaction between different limbs causes all sorts of edge cases that even I don't understand. If you understand how to do this in a way that is more efficient than calling 1-argument `prevfloat`/`nextfloat` repeatedly, I would love to hear your suggested algorithm and proof of correctness. Otherwise, I consider it a feature, not a bug, that a user has to call 1-argument `prevfloat`/`nextfloat` repeatedly, so they are consciously aware that a loop is happening, and this is not a constant-time operation, like it is for `IEEEFloat` types.
